### ISSUE TITLE
Add support for Xss X11 screen saver API

### ISSUE THREAD

**Issue by perrin4869** [Zygo/xscreensaver#12]
From `man Xss`, a screensaver can be suspended. Programs live `mpv` make use of this API to suspend the screensaver while a video is playing, but `xscreensaver` doesn't seem to respect this.
Is there a reason this hasn't been added, and would you be open to a PR adding this feature?

**Comment by ildar** [comment]
I am sorry, couldn't fully understand.
1. where's `man Xss`? don't see this man page.
2. is this (maybe) related to https://github.com/Zygo/xscreensaver/issues/10
?

**Comment by perrin4869** [comment]
Well I talked to Jamie and he isn't interested in adding support for this, so I guess it's irrelevant now.
`man Xss` in my system comes from `libXScrnSaver-1.2.3`

```
❯ grep Xss /var/log/packages/*
/var/log/packages/libXScrnSaver-1.2.3-x86_64-3:usr/lib64/libXss.so.1.0.0
/var/log/packages/libXScrnSaver-1.2.3-x86_64-3:usr/man/man3/Xss.3.gz
```

You can find some more info [here](https://man.archlinux.org/man/community/mpv/mpv.1.en#Disabling_Screensaver)

**Comment by Jaldebehot** [comment]
What did you learn from Jamie about this? The manpage says mpv makes no attempt to suspend the screensaver but that isn't true since it's trying to do so through the so-called XScreenSaver API (part of the X server). Is it better somehow if mpv used the d-bus interface instead? The "switch user" button in xscreensaver doesn't even use d-bus either, for example I heard it was hardcoded to call GDM rather than using org.freedesktop.DisplayManager.Seat.SwitchToGreeter

**Comment by perrin4869** [comment]
regarding Xss, Jamie said:

```
That is the "MIT-SCREEN-SAVER" extension, and it is garbage. It doesn't do what you think it does, it crashes the server a lot, and it basically hasn't been maintained since the early 90s.

So, unfortunately -- yes, there is a very good reason that I dropped support for that many years ago.
```

I personally use an mpv lua script to keep the screensaver off, please see https://github.com/perrin4869/dotfiles/blob/master/home/.config/mpv/scripts/screensaver.lua

**Comment by Jaldebehot** [comment]
Thank you for providing the context. I noticed xss is included in my distribution of X11 as provided by Arch Linux, but I didn't know these details until now. Hopefully someday mpv can use a different API ootb on X11 to suspend the screensaver...

**Comment by perrin4869** [comment]
I think that a plugin for mpv that makes use of the dbus `org.freedesktop.screensaver` service would actually be the best way to go forward. It could be a lua script that calls `dbus-send` periodically, similar to my example above, or a native plugin such as [mpv-mpris](https://github.com/hoyon/mpv-mpris) that uses the dbus C library to call the service
