### ISSUE TITLE
Please update for xscreensaver 5.37

### ISSUE THREAD

**Issue by micolous** [Zygo/xscreensaver#3]
https://www.jwz.org/xscreensaver/xscreensaver-5.37.tar.gz

Thanks!

**Comment by Zygo** [comment]
5.37 was already there, but not on the master branch.

Some earlier revisions were missing when the repo's master branch was first pushed.  To avoid disrupting downstream repos based on the master branch, xscreensaver revisions after 5.08 are found in the master2 branch.  There are two problems with this:

1.  It's weird.  Normally 'master' is the head branch.  This quirk has to be explained to everyone who isn't using the github UI, or they have to figure it out on their own.

2.  None of the github forks seem to be using master, so it's not clear whether any downstream repos following master still exist to be disrupted by the insertion of an old revision.

In that case, we can just drop the old master branch (I will leave a tag behind for audits) and make master the head branch of the repo (with 5.37).

**Comment by micolous** [comment]
You can update the default branch in GitHub settings, that would point people to `master2`.
